package com.cajasullana.bpmprojects.requerimientobpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "DOI")
   private java.lang.String dni;
   @org.kie.api.definition.type.Label(value = "Nombres")
   private java.lang.String nombres;
   @org.kie.api.definition.type.Label(value = "Apellidos")
   private java.lang.String apellidos;
   @org.kie.api.definition.type.Label(value = "Raz\u00F3n Social")
   private java.lang.String razonSocial;
   @org.kie.api.definition.type.Label(value = "Direcci\u00F3n")
   private java.lang.String direccion;
   @org.kie.api.definition.type.Label(value = "Tel\u00E9fono")
   private java.lang.String telefono;
   @org.kie.api.definition.type.Label(value = "Tipo de Requerimiento")
   private com.cajasullana.bpmprojects.requerimientobpm.TipoRequerimiento tipoRequerimiento;
   @org.kie.api.definition.type.Label(value = "Detalle")
   private java.lang.String detalle;

   public Cliente()
   {
   }

   public java.lang.String getDni()
   {
      return this.dni;
   }

   public void setDni(java.lang.String dni)
   {
      this.dni = dni;
   }

   public java.lang.String getNombres()
   {
      return this.nombres;
   }

   public void setNombres(java.lang.String nombres)
   {
      this.nombres = nombres;
   }

   public java.lang.String getApellidos()
   {
      return this.apellidos;
   }

   public void setApellidos(java.lang.String apellidos)
   {
      this.apellidos = apellidos;
   }

   public java.lang.String getRazonSocial()
   {
      return this.razonSocial;
   }

   public void setRazonSocial(java.lang.String razonSocial)
   {
      this.razonSocial = razonSocial;
   }

   public java.lang.String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(java.lang.String direccion)
   {
      this.direccion = direccion;
   }

   public java.lang.String getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(java.lang.String telefono)
   {
      this.telefono = telefono;
   }

   public com.cajasullana.bpmprojects.requerimientobpm.TipoRequerimiento getTipoRequerimiento()
   {
      return this.tipoRequerimiento;
   }

   public void setTipoRequerimiento(
         com.cajasullana.bpmprojects.requerimientobpm.TipoRequerimiento tipoRequerimiento)
   {
      this.tipoRequerimiento = tipoRequerimiento;
   }

   public java.lang.String getDetalle()
   {
      return this.detalle;
   }

   public void setDetalle(java.lang.String detalle)
   {
      this.detalle = detalle;
   }

   public Cliente(
         java.lang.String dni,
         java.lang.String nombres,
         java.lang.String apellidos,
         java.lang.String razonSocial,
         java.lang.String direccion,
         java.lang.String telefono,
         com.cajasullana.bpmprojects.requerimientobpm.TipoRequerimiento tipoRequerimiento,
         java.lang.String detalle)
   {
      this.dni = dni;
      this.nombres = nombres;
      this.apellidos = apellidos;
      this.razonSocial = razonSocial;
      this.direccion = direccion;
      this.telefono = telefono;
      this.tipoRequerimiento = tipoRequerimiento;
      this.detalle = detalle;
   }

}