package com.cajasullana.bpmprojects.requerimientobpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("DOI")
   private java.lang.String dni;
   @org.kie.api.definition.type.Label("Nombres")
   private java.lang.String nombres;
   @org.kie.api.definition.type.Label("Apellidos")
   private java.lang.String apellidos;
   @org.kie.api.definition.type.Label("Raz\u00F3n Social")
   private java.lang.String razonSocial;
   @org.kie.api.definition.type.Label("Direcci\u00F3n")
   private java.lang.String direccion;
   @org.kie.api.definition.type.Label("Tel\u00E9fono")
   private java.lang.String telefono;
   @org.kie.api.definition.type.Label("Email")
   private java.lang.String email;

   @org.kie.api.definition.type.Label(value = "Es Cliente")
   private java.lang.Boolean clientesi;

   @org.kie.api.definition.type.Label(value = "Tipo Documento")
   private java.lang.String tipoDoi;

   public Cliente()
   {
   }

   public java.lang.String getDni()
   {
      return this.dni;
   }

   public void setDni(java.lang.String dni)
   {
      this.dni = dni;
   }

   public java.lang.String getNombres()
   {
      return this.nombres;
   }

   public void setNombres(java.lang.String nombres)
   {
      this.nombres = nombres;
   }

   public java.lang.String getApellidos()
   {
      return this.apellidos;
   }

   public void setApellidos(java.lang.String apellidos)
   {
      this.apellidos = apellidos;
   }

   public java.lang.String getRazonSocial()
   {
      return this.razonSocial;
   }

   public void setRazonSocial(java.lang.String razonSocial)
   {
      this.razonSocial = razonSocial;
   }

   public java.lang.String getDireccion()
   {
      return this.direccion;
   }

   public void setDireccion(java.lang.String direccion)
   {
      this.direccion = direccion;
   }

   public java.lang.String getTelefono()
   {
      return this.telefono;
   }

   public void setTelefono(java.lang.String telefono)
   {
      this.telefono = telefono;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.Boolean getClientesi()
   {
      return this.clientesi;
   }

   public void setClientesi(java.lang.Boolean clientesi)
   {
      this.clientesi = clientesi;
   }

   public java.lang.String getTipoDoi()
   {
      return this.tipoDoi;
   }

   public void setTipoDoi(java.lang.String tipoDoi)
   {
      this.tipoDoi = tipoDoi;
   }

   public Cliente(java.lang.String dni, java.lang.String nombres,
         java.lang.String apellidos, java.lang.String razonSocial,
         java.lang.String direccion, java.lang.String telefono,
         java.lang.String email, java.lang.Boolean clientesi,
         java.lang.String tipoDoi)
   {
      this.dni = dni;
      this.nombres = nombres;
      this.apellidos = apellidos;
      this.razonSocial = razonSocial;
      this.direccion = direccion;
      this.telefono = telefono;
      this.email = email;
      this.clientesi = clientesi;
      this.tipoDoi = tipoDoi;
   }

}