package com.cajasullana.bpmprojects.requerimientobpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Direcciona implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "C\u00F3digo de Usuario")
   private java.lang.String codigoUsuario;
   @org.kie.api.definition.type.Label(value = "Nombres")
   private java.lang.String nombres;

   public Direcciona()
   {
   }

   public java.lang.String getCodigoUsuario()
   {
      return this.codigoUsuario;
   }

   public void setCodigoUsuario(java.lang.String codigoUsuario)
   {
      this.codigoUsuario = codigoUsuario;
   }

   public java.lang.String getNombres()
   {
      return this.nombres;
   }

   public void setNombres(java.lang.String nombres)
   {
      this.nombres = nombres;
   }

   public Direcciona(java.lang.String codigoUsuario, java.lang.String nombres)
   {
      this.codigoUsuario = codigoUsuario;
      this.nombres = nombres;
   }

}