package com.cajasullana.bpmprojects.requerimientobpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Requerimiento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Fecha")
   private java.util.Date fecha;
   @org.kie.api.definition.type.Label("Cliente")
   private com.cajasullana.bpmprojects.requerimientobpm.Cliente cliente;

   public Requerimiento()
   {
   }

   public java.util.Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.util.Date fecha)
   {
      this.fecha = fecha;
   }

   public com.cajasullana.bpmprojects.requerimientobpm.Cliente getCliente()
   {
      return this.cliente;
   }

   public void setCliente(
         com.cajasullana.bpmprojects.requerimientobpm.Cliente cliente)
   {
      this.cliente = cliente;
   }

   public Requerimiento(java.util.Date fecha,
         com.cajasullana.bpmprojects.requerimientobpm.Cliente cliente)
   {
      this.fecha = fecha;
      this.cliente = cliente;
   }

}