package com.cajasullana.bpmprojects.requerimientobpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TipoRequerimiento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nombre")
   private java.lang.String nombre;

   @org.kie.api.definition.type.Label(value = "Tiempo de Atenci\u00F3n")
   private java.lang.Integer tiempoAtencion;

   public TipoRequerimiento()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public java.lang.Integer getTiempoAtencion()
   {
      return this.tiempoAtencion;
   }

   public void setTiempoAtencion(java.lang.Integer tiempoAtencion)
   {
      this.tiempoAtencion = tiempoAtencion;
   }

   public TipoRequerimiento(java.lang.String nombre,
         java.lang.Integer tiempoAtencion)
   {
      this.nombre = nombre;
      this.tiempoAtencion = tiempoAtencion;
   }

}