package com.cajasullana.bpmprojects.requerimientobpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TipoRequerimiento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Id")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "Tiempo de Atenci\u00F3n")
   private java.lang.Integer tiempoAtencion;

   public TipoRequerimiento()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.Integer getTiempoAtencion()
   {
      return this.tiempoAtencion;
   }

   public void setTiempoAtencion(java.lang.Integer tiempoAtencion)
   {
      this.tiempoAtencion = tiempoAtencion;
   }

   public TipoRequerimiento(java.lang.String id,
         java.lang.Integer tiempoAtencion)
   {
      this.id = id;
      this.tiempoAtencion = tiempoAtencion;
   }

}