package com.cajasullana.bpmprojects.reclamosbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BienContratado implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Tipo")
   private java.lang.String tipo;
   @org.kie.api.definition.type.Label(value = "Monto Reclamado")
   private java.lang.Double montoReclamado;
   @org.kie.api.definition.type.Label(value = "Descripcion")
   private java.lang.String descripcion;

   public BienContratado()
   {
   }

   public java.lang.String getTipo()
   {
      return this.tipo;
   }

   public void setTipo(java.lang.String tipo)
   {
      this.tipo = tipo;
   }

   public java.lang.Double getMontoReclamado()
   {
      return this.montoReclamado;
   }

   public void setMontoReclamado(java.lang.Double montoReclamado)
   {
      this.montoReclamado = montoReclamado;
   }

   public java.lang.String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(java.lang.String descripcion)
   {
      this.descripcion = descripcion;
   }

   public BienContratado(java.lang.String tipo,
         java.lang.Double montoReclamado, java.lang.String descripcion)
   {
      this.tipo = tipo;
      this.montoReclamado = montoReclamado;
      this.descripcion = descripcion;
   }

}