package com.cajasullana.bpmprojects.reclamosbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Estado implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Nombre")
   private java.lang.String nombre;

   public Estado()
   {
   }

   public java.lang.String getNombre()
   {
      return this.nombre;
   }

   public void setNombre(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

   public Estado(java.lang.String nombre)
   {
      this.nombre = nombre;
   }

}