package com.cajasullana.bpmprojects.reclamosbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductoServicio implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ProductoServicio() {
    }

}