package com.cajasullana.bpmprojects.reclamosbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Requerimiento implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Fecha")
   private java.util.Date fecha;
   @org.kie.api.definition.type.Label(value = "Bien Contratado")
   private com.cajasullana.bpmprojects.reclamosbpm.BienContratado bienContratado;
   @org.kie.api.definition.type.Label(value = "Detalle Reclamo")
   private com.cajasullana.bpmprojects.reclamosbpm.DetalleReclamo detalleReclamo;
   @org.kie.api.definition.type.Label(value = "Producto Servicio")
   private com.cajasullana.bpmprojects.reclamosbpm.ProductoServicio productoServicio;
   @org.kie.api.definition.type.Label(value = "N\u00FAmero de Cuenta")
   private java.lang.String numeroCuenta;
   @org.kie.api.definition.type.Label(value = "N\u00FAmero de Tarjeta")
   private java.lang.String numeroTarjeta;
   @org.kie.api.definition.type.Label(value = "Tipo de Seguro")
   private java.lang.String tipoSeguro;
   @org.kie.api.definition.type.Label(value = "Otros")
   private java.lang.String otros;
   @org.kie.api.definition.type.Label(value = "Moneda")
   private java.lang.String moneda;
   @org.kie.api.definition.type.Label(value = "Motivo del Reclamo")
   private java.lang.String motivoReclamo;
   @org.kie.api.definition.type.Label(value = "Detalle")
   private java.lang.String detalle;
   @org.kie.api.definition.type.Label(value = "Pedido")
   private java.lang.String pedido;
   @org.kie.api.definition.type.Label(value = "Observaciones")
   private java.lang.String observaciones;
   @org.kie.api.definition.type.Label(value = "Respuesta")
   private com.cajasullana.bpmprojects.reclamosbpm.Respuesta respuesta;

   public Requerimiento()
   {
   }

   public java.util.Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.util.Date fecha)
   {
      this.fecha = fecha;
   }

   public com.cajasullana.bpmprojects.reclamosbpm.BienContratado getBienContratado()
   {
      return this.bienContratado;
   }

   public void setBienContratado(
         com.cajasullana.bpmprojects.reclamosbpm.BienContratado bienContratado)
   {
      this.bienContratado = bienContratado;
   }

   public com.cajasullana.bpmprojects.reclamosbpm.DetalleReclamo getDetalleReclamo()
   {
      return this.detalleReclamo;
   }

   public void setDetalleReclamo(
         com.cajasullana.bpmprojects.reclamosbpm.DetalleReclamo detalleReclamo)
   {
      this.detalleReclamo = detalleReclamo;
   }

   public com.cajasullana.bpmprojects.reclamosbpm.ProductoServicio getProductoServicio()
   {
      return this.productoServicio;
   }

   public void setProductoServicio(
         com.cajasullana.bpmprojects.reclamosbpm.ProductoServicio productoServicio)
   {
      this.productoServicio = productoServicio;
   }

   public java.lang.String getNumeroCuenta()
   {
      return this.numeroCuenta;
   }

   public void setNumeroCuenta(java.lang.String numeroCuenta)
   {
      this.numeroCuenta = numeroCuenta;
   }

   public java.lang.String getNumeroTarjeta()
   {
      return this.numeroTarjeta;
   }

   public void setNumeroTarjeta(java.lang.String numeroTarjeta)
   {
      this.numeroTarjeta = numeroTarjeta;
   }

   public java.lang.String getTipoSeguro()
   {
      return this.tipoSeguro;
   }

   public void setTipoSeguro(java.lang.String tipoSeguro)
   {
      this.tipoSeguro = tipoSeguro;
   }

   public java.lang.String getOtros()
   {
      return this.otros;
   }

   public void setOtros(java.lang.String otros)
   {
      this.otros = otros;
   }

   public java.lang.String getMoneda()
   {
      return this.moneda;
   }

   public void setMoneda(java.lang.String moneda)
   {
      this.moneda = moneda;
   }

   public java.lang.String getMotivoReclamo()
   {
      return this.motivoReclamo;
   }

   public void setMotivoReclamo(java.lang.String motivoReclamo)
   {
      this.motivoReclamo = motivoReclamo;
   }

   public java.lang.String getDetalle()
   {
      return this.detalle;
   }

   public void setDetalle(java.lang.String detalle)
   {
      this.detalle = detalle;
   }

   public java.lang.String getPedido()
   {
      return this.pedido;
   }

   public void setPedido(java.lang.String pedido)
   {
      this.pedido = pedido;
   }

   public java.lang.String getObservaciones()
   {
      return this.observaciones;
   }

   public void setObservaciones(java.lang.String observaciones)
   {
      this.observaciones = observaciones;
   }

   public com.cajasullana.bpmprojects.reclamosbpm.Respuesta getRespuesta()
   {
      return this.respuesta;
   }

   public void setRespuesta(
         com.cajasullana.bpmprojects.reclamosbpm.Respuesta respuesta)
   {
      this.respuesta = respuesta;
   }

   public Requerimiento(
         java.util.Date fecha,
         com.cajasullana.bpmprojects.reclamosbpm.BienContratado bienContratado,
         com.cajasullana.bpmprojects.reclamosbpm.DetalleReclamo detalleReclamo,
         com.cajasullana.bpmprojects.reclamosbpm.ProductoServicio productoServicio,
         java.lang.String numeroCuenta, java.lang.String numeroTarjeta,
         java.lang.String tipoSeguro, java.lang.String otros,
         java.lang.String moneda, java.lang.String motivoReclamo,
         java.lang.String detalle, java.lang.String pedido,
         java.lang.String observaciones,
         com.cajasullana.bpmprojects.reclamosbpm.Respuesta respuesta)
   {
      this.fecha = fecha;
      this.bienContratado = bienContratado;
      this.detalleReclamo = detalleReclamo;
      this.productoServicio = productoServicio;
      this.numeroCuenta = numeroCuenta;
      this.numeroTarjeta = numeroTarjeta;
      this.tipoSeguro = tipoSeguro;
      this.otros = otros;
      this.moneda = moneda;
      this.motivoReclamo = motivoReclamo;
      this.detalle = detalle;
      this.pedido = pedido;
      this.observaciones = observaciones;
      this.respuesta = respuesta;
   }

}