package com.cajasullana.bpmprojects.reclamosbpm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Respuesta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Fecha")
   private java.util.Date fecha;
   @org.kie.api.definition.type.Label(value = "Forma")
   private java.lang.String forma;

   public Respuesta()
   {
   }

   public java.util.Date getFecha()
   {
      return this.fecha;
   }

   public void setFecha(java.util.Date fecha)
   {
      this.fecha = fecha;
   }

   public java.lang.String getForma()
   {
      return this.forma;
   }

   public void setForma(java.lang.String forma)
   {
      this.forma = forma;
   }

   public Respuesta(java.util.Date fecha, java.lang.String forma)
   {
      this.fecha = fecha;
      this.forma = forma;
   }

}